#create python script that declares the variable in which print all information about  ypur self like
# (name ,gender,Adresss, degree etc )
name='my name is samra naz'
age='my age is 21'
gender=' i am a femail'
address='  my address is islamabad abc'
degree=' my degree is  BSCS'
dob= 'my date of birth is 29_5_2002'
marital_status='i am single'
email='my email is naazsamra01@gmail.com'
nationality=' my nationality is pakistani'
hobbies= 'my hobbies is coding , reading, learning'
print(f'name:{name}')
print(f'age:{age}\ngender:{gender}\naddress:{address}\ndegree:{degree}\ndob:{dob}')
print(f'marital_status:{marital_status}\nemail:{email}\nnationality:{nationality}\nhobbies:{hobbies}')
